// Code generated by goctl. DO NOT EDIT.
// Source: product_rpc.proto

package server

import (
	"context"

	"github.com/zhanghongliang12/lebron/apps/product/product_rpc/internal/logic"
	"github.com/zhanghongliang12/lebron/apps/product/product_rpc/internal/svc"
	"github.com/zhanghongliang12/lebron/apps/product/product_rpc/product_rpc"
)

type ProductRpcServer struct {
	svcCtx *svc.ServiceContext
	product_rpc.UnimplementedProductRpcServer
}

func NewProductRpcServer(svcCtx *svc.ServiceContext) *ProductRpcServer {
	return &ProductRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductRpcServer) Ping(ctx context.Context, in *product_rpc.Request) (*product_rpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
