// Code generated by goctl. DO NOT EDIT.
// Source: pay_rpc.proto

package server

import (
	"context"

	"github.com/zhanghongliang12/lebron/apps/pay/pay_rpc/internal/logic"
	"github.com/zhanghongliang12/lebron/apps/pay/pay_rpc/internal/svc"
	"github.com/zhanghongliang12/lebron/apps/pay/pay_rpc/pay_rpc"
)

type PayRpcServer struct {
	svcCtx *svc.ServiceContext
	pay_rpc.UnimplementedPayRpcServer
}

func NewPayRpcServer(svcCtx *svc.ServiceContext) *PayRpcServer {
	return &PayRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *PayRpcServer) Ping(ctx context.Context, in *pay_rpc.Request) (*pay_rpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
