// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: pay_rpc.proto

package pay_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PayRpc_Ping_FullMethodName = "/pay_rpc.Pay_rpc/Ping"
)

// PayRpcClient is the client API for PayRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayRpcClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type payRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewPayRpcClient(cc grpc.ClientConnInterface) PayRpcClient {
	return &payRpcClient{cc}
}

func (c *payRpcClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, PayRpc_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayRpcServer is the server API for PayRpc service.
// All implementations must embed UnimplementedPayRpcServer
// for forward compatibility
type PayRpcServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedPayRpcServer()
}

// UnimplementedPayRpcServer must be embedded to have forward compatible implementations.
type UnimplementedPayRpcServer struct {
}

func (UnimplementedPayRpcServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedPayRpcServer) mustEmbedUnimplementedPayRpcServer() {}

// UnsafePayRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayRpcServer will
// result in compilation errors.
type UnsafePayRpcServer interface {
	mustEmbedUnimplementedPayRpcServer()
}

func RegisterPayRpcServer(s grpc.ServiceRegistrar, srv PayRpcServer) {
	s.RegisterService(&PayRpc_ServiceDesc, srv)
}

func _PayRpc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayRpcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayRpc_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayRpcServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// PayRpc_ServiceDesc is the grpc.ServiceDesc for PayRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PayRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pay_rpc.Pay_rpc",
	HandlerType: (*PayRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _PayRpc_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pay_rpc.proto",
}
