// Code generated by goctl. DO NOT EDIT.
// Source: reply_rpc.proto

package server

import (
	"context"

	"github.com/zhanghongliang12/lebron/apps/reply/reply_rpc/internal/logic"
	"github.com/zhanghongliang12/lebron/apps/reply/reply_rpc/internal/svc"
	"github.com/zhanghongliang12/lebron/apps/reply/reply_rpc/reply_rpc"
)

type ReplyRpcServer struct {
	svcCtx *svc.ServiceContext
	reply_rpc.UnimplementedReplyRpcServer
}

func NewReplyRpcServer(svcCtx *svc.ServiceContext) *ReplyRpcServer {
	return &ReplyRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *ReplyRpcServer) Ping(ctx context.Context, in *reply_rpc.Request) (*reply_rpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
