// Code generated by goctl. DO NOT EDIT.
// Source: order_rpc.proto

package server

import (
	"context"

	"github.com/zhanghongliang12/lebron/apps/order/order_rpc/internal/logic"
	"github.com/zhanghongliang12/lebron/apps/order/order_rpc/internal/svc"
	"github.com/zhanghongliang12/lebron/apps/order/order_rpc/order_rpc"
)

type OrderRpcServer struct {
	svcCtx *svc.ServiceContext
	order_rpc.UnimplementedOrderRpcServer
}

func NewOrderRpcServer(svcCtx *svc.ServiceContext) *OrderRpcServer {
	return &OrderRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderRpcServer) Ping(ctx context.Context, in *order_rpc.Request) (*order_rpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
