// Code generated by goctl. DO NOT EDIT.
// Source: user_rpc.proto

package server

import (
	"context"
	"github.com/zhoushuguang/lebron/apps/user/rpc/user"

	"github.com/zhanghongliang12/lebron/apps/user/user_rpc/internal/logic"
	"github.com/zhanghongliang12/lebron/apps/user/user_rpc/internal/svc"
	"github.com/zhanghongliang12/lebron/apps/user/user_rpc/user_rpc"
)

type UserRpcServer struct {
	svcCtx *svc.ServiceContext
	user_rpc.UnimplementedUserServer
}

func NewUserRpcServer(svcCtx *svc.ServiceContext) *UserRpcServer {
	return &UserRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *UserRpcServer) Login(ctx context.Context, in *user.LoginRequest) (*user.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}