// Code generated by goctl. DO NOT EDIT.
// Source: recommend_rpc.proto

package server

import (
	"context"

	"github.com/zhanghongliang12/lebron/apps/recommend/recommend_rpc/internal/logic"
	"github.com/zhanghongliang12/lebron/apps/recommend/recommend_rpc/internal/svc"
	"github.com/zhanghongliang12/lebron/apps/recommend/recommend_rpc/recommend_rpc"
)

type RecommendRpcServer struct {
	svcCtx *svc.ServiceContext
	recommend_rpc.UnimplementedRecommendRpcServer
}

func NewRecommendRpcServer(svcCtx *svc.ServiceContext) *RecommendRpcServer {
	return &RecommendRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *RecommendRpcServer) Ping(ctx context.Context, in *recommend_rpc.Request) (*recommend_rpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
