// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: recommend_rpc.proto

package recommend_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RecommendRpc_Ping_FullMethodName = "/recommend_rpc.Recommend_rpc/Ping"
)

// RecommendRpcClient is the client API for RecommendRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RecommendRpcClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type recommendRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommendRpcClient(cc grpc.ClientConnInterface) RecommendRpcClient {
	return &recommendRpcClient{cc}
}

func (c *recommendRpcClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, RecommendRpc_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecommendRpcServer is the server API for RecommendRpc service.
// All implementations must embed UnimplementedRecommendRpcServer
// for forward compatibility
type RecommendRpcServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedRecommendRpcServer()
}

// UnimplementedRecommendRpcServer must be embedded to have forward compatible implementations.
type UnimplementedRecommendRpcServer struct {
}

func (UnimplementedRecommendRpcServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedRecommendRpcServer) mustEmbedUnimplementedRecommendRpcServer() {}

// UnsafeRecommendRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecommendRpcServer will
// result in compilation errors.
type UnsafeRecommendRpcServer interface {
	mustEmbedUnimplementedRecommendRpcServer()
}

func RegisterRecommendRpcServer(s grpc.ServiceRegistrar, srv RecommendRpcServer) {
	s.RegisterService(&RecommendRpc_ServiceDesc, srv)
}

func _RecommendRpc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecommendRpcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecommendRpc_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecommendRpcServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// RecommendRpc_ServiceDesc is the grpc.ServiceDesc for RecommendRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecommendRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recommend_rpc.Recommend_rpc",
	HandlerType: (*RecommendRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _RecommendRpc_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recommend_rpc.proto",
}
