// Code generated by goctl. DO NOT EDIT.
// Source: seckill_rpc.proto

package server

import (
	"context"

	"github.com/zhanghongliang12/lebron/apps/seckill/seckill_rpc/internal/logic"
	"github.com/zhanghongliang12/lebron/apps/seckill/seckill_rpc/internal/svc"
	"github.com/zhanghongliang12/lebron/apps/seckill/seckill_rpc/seckill_rpc"
)

type SeckillRpcServer struct {
	svcCtx *svc.ServiceContext
	seckill_rpc.UnimplementedSeckillRpcServer
}

func NewSeckillRpcServer(svcCtx *svc.ServiceContext) *SeckillRpcServer {
	return &SeckillRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *SeckillRpcServer) Ping(ctx context.Context, in *seckill_rpc.Request) (*seckill_rpc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
