// Code generated by goctl. DO NOT EDIT.
// Source: cart_rpc.proto

package cartrpcclient

import (
	"context"

	"github.com/zhanghongliang12/lebron/apps/cart/cart_rpc/cart_rpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = cart_rpc.Request
	Response = cart_rpc.Response

	CartRpc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultCartRpc struct {
		cli zrpc.Client
	}
)

func NewCartRpc(cli zrpc.Client) CartRpc {
	return &defaultCartRpc{
		cli: cli,
	}
}

func (m *defaultCartRpc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := cart_rpc.NewCartRpcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
