// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: order_rpc.proto

package order_rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	OrderRpc_Ping_FullMethodName = "/order_rpc.Order_rpc/Ping"
)

// OrderRpcClient is the client API for OrderRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderRpcClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type orderRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderRpcClient(cc grpc.ClientConnInterface) OrderRpcClient {
	return &orderRpcClient{cc}
}

func (c *orderRpcClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, OrderRpc_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderRpcServer is the server API for OrderRpc service.
// All implementations must embed UnimplementedOrderRpcServer
// for forward compatibility
type OrderRpcServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedOrderRpcServer()
}

// UnimplementedOrderRpcServer must be embedded to have forward compatible implementations.
type UnimplementedOrderRpcServer struct {
}

func (UnimplementedOrderRpcServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedOrderRpcServer) mustEmbedUnimplementedOrderRpcServer() {}

// UnsafeOrderRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderRpcServer will
// result in compilation errors.
type UnsafeOrderRpcServer interface {
	mustEmbedUnimplementedOrderRpcServer()
}

func RegisterOrderRpcServer(s grpc.ServiceRegistrar, srv OrderRpcServer) {
	s.RegisterService(&OrderRpc_ServiceDesc, srv)
}

func _OrderRpc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderRpcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderRpc_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderRpcServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderRpc_ServiceDesc is the grpc.ServiceDesc for OrderRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order_rpc.Order_rpc",
	HandlerType: (*OrderRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _OrderRpc_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order_rpc.proto",
}
